from ast_nodes import AndCondition, Comparison, Fact


def condition_to_string(condition):

    if isinstance(condition, AndCondition):

        left = condition_to_string(condition.left)
        right = condition_to_string(condition.right)

        return f"({left} AND {right})"

    if isinstance(condition, Comparison):

        return f"{condition.identifier} {condition.operator} {condition.value}"

    if isinstance(condition, Fact):

        return condition.identifier

    return ""


def get_condition_facts(condition):

    if isinstance(condition, Fact):

        return {condition.identifier}

    if isinstance(condition, AndCondition):

        return (
            get_condition_facts(condition.left)
            |
            get_condition_facts(condition.right)
        )

    return set()


def analyze(program, variables, initial_facts):

    messages = []

    # =====================================================
    # REDUNDANT RULES
    # =====================================================

    seen = {}

    for rule in program.rules:

        key = (
            condition_to_string(rule.condition),
            rule.action.identifier
        )

        if key not in seen:
            seen[key] = []

        seen[key].append(rule.name)

    redundant_rules = set()

    for rule_names in seen.values():

        if len(rule_names) > 1:

            messages.append(
                f"Redundant rules: {', '.join(rule_names)}"
            )

            for name in rule_names:
                redundant_rules.add(name)

    # =====================================================
    # CONFLICTS
    # =====================================================

    actions = {}

    for rule in program.rules:

        action_id = rule.action.identifier

        if action_id not in actions:
            actions[action_id] = []

        actions[action_id].append(rule.name)

    for action_id, rule_names in actions.items():

        if len(rule_names) > 1:

            if not all(name in redundant_rules for name in rule_names):

                messages.append(
                    f"Action {action_id} generated by {', '.join(rule_names)}"
                )

    # =====================================================
    # POTENTIALLY INACTIVE RULES
    # =====================================================

    used_facts = set()

    for rule in program.rules:

        used_facts.update(
            get_condition_facts(rule.condition)
        )

    for rule in program.rules:

        action_id = rule.action.identifier

        needed_facts = get_condition_facts(rule.condition)

        # SOLO reglas aisladas con comparaciones
        if (
            not needed_facts
            and action_id not in used_facts
            and len(program.rules) > 2
        ):

            messages.append(
                f"Potentially inactive rule: {rule.name}"
            )

    return messages